version: '3.9'

services:
  db:
    image: "mysql:8.1.0"
    restart: always
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    expose:
      - "${MYSQL_PORT}"
    volumes:
      - "data:/var/lib/mysql"

  backend:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    volumes:
      - type: bind
        source: "~/Django/epsilonvi_bot/app/"
        target: "/app"
      - ".env:/app/.env"
    depends_on:
      - db

volumes:
  # app:
  data:
  .env: